// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nlttemvyhayvixjbtfnd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5sdHRlbXZ5aGF5dml4amJ0Zm5kIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg2MjAzMjAsImV4cCI6MjA2NDE5NjMyMH0.T5knb74_ICF7oVqRxlQKPuQu2-s5WLNlIrIaQ1rtAxc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);